import { getDb } from '@/lib/db/database'
import { getAppConfig } from '@/lib/db/queries'
import type { ExtractedZone } from '@/lib/gemini/text-extractor'

const LONG_WORD_LANGUAGES = ['de', 'fi', 'hu', 'nl', 'hr', 'el']

const LANGUAGE_NAMES: Record<string, string> = {
  fr: 'French', nl: 'Dutch', de: 'German', cs: 'Czech', da: 'Danish',
  es: 'Spanish', fi: 'Finnish', en: 'English', el: 'Greek', hr: 'Croatian',
  hu: 'Hungarian', it: 'Italian', lt: 'Lithuanian', lv: 'Latvian',
  pl: 'Polish', pt: 'Portuguese', ro: 'Romanian', sv: 'Swedish',
  sl: 'Slovenian', sk: 'Slovak',
}

export const DEFAULT_GOOGLE_RENDER =
  '- Render each quoted text exactly — character for character, same case\n' +
  '- Match the original font weight, color, size, and typographic style for each zone\n' +
  '- Preserve all visual elements: layout, background, colors, images, graphics\n' +
  '- Do not retranslate — the quoted texts are final'

function getGoogleRenderRules(): string {
  try { return getAppConfig(getDb(), 'prompt_google_render') || DEFAULT_GOOGLE_RENDER } catch { return DEFAULT_GOOGLE_RENDER }
}

export const DEFAULT_BASE_PROMPT =
  'You are a native marketing copywriter adapting an advertising visual from French to {language}.\n' +
  'Do NOT translate word-for-word. Adapt the message so it reads as if a professional {language} copywriter originally wrote it — natural, idiomatic, impactful.\n' +
  '- Use natural, idiomatic {language} as used in advertising and e-commerce\n' +
  '- Choose ONE consistent register (informal/tu for B2C unless the brand requires formal) and apply it to ALL text elements in the image\n' +
  '- Prioritize naturalness and marketing impact over literal accuracy\n' +
  '- Preserve the layout, colors, fonts, and design exactly as they are — only change the text content'

/**
 * Google-recommended "text-first" mode: translations were pre-generated by a text model.
 * Uses explicit quoted text per zone — Google's recommended approach for best text rendering.
 */
export function buildGoogleModePrompt(
  translations: Record<string, string>,  // zone_label -> translated text
  targetLanguage: string,
  customPrompt?: string,
  extractedZones?: Record<string, ExtractedZone>
): string {
  const langName = LANGUAGE_NAMES[targetLanguage] || targetLanguage
  const parts: string[] = []

  if (customPrompt?.trim()) {
    parts.push(`IMPORTANT corrections to apply:\n${customPrompt.trim()}`)
  }

  const textList = Object.entries(translations)
    .map(([zone, text]) => {
      const z = extractedZones?.[zone]
      if (z) {
        return `  - ${zone}: render "${text}" — ${z.weight}, ${z.case}, color: ${z.color}, ${z.size} size`
      }
      return `  - ${zone}: render "${text}" in the same typographic style as the original`
    })
    .join('\n')

  parts.push(
    `Reproduce this French advertising image adapted to ${langName}.\n\n` +
    `A language expert has pre-translated all text zones. Render each one exactly as quoted:\n\n` +
    `${textList}\n\n` +
    `Critical rules:\n` +
    getGoogleRenderRules()
  )

  if (LONG_WORD_LANGUAGES.includes(targetLanguage)) {
    parts.push(
      `Note: ${langName} text may be longer. Reduce font size or adjust letter spacing as needed — never truncate.`
    )
  }

  return parts.join('\n\n')
}

/**
 * Correction mode: input image is already translated. Apply targeted fixes only.
 */
export function buildGoogleModeCorrectionPrompt(correctionInstructions: string): string {
  return correctionInstructions.trim()
}

interface PromptOptions {
  targetLanguage: string
  customPrompt?: string
  basePrompt?: string
  glossaryTerms?: { source: string; target: string }[]
  glossaryHints?: string[]  // Precision mode: contextual hints filtered for this image
  languageRules?: string[]  // Language-wide style/usage rules
}

export function buildTranslationPrompt(options: PromptOptions): string {
  const { targetLanguage, customPrompt, basePrompt, glossaryTerms, glossaryHints, languageRules } = options
  const langName = LANGUAGE_NAMES[targetLanguage] || targetLanguage

  const parts: string[] = []

  // Custom corrections take priority — stated first
  if (customPrompt && customPrompt.trim()) {
    parts.push(
      `IMPORTANT corrections to apply first:\n${customPrompt.trim()}`
    )
  }

  // System prompt — use admin-configured base prompt if set, else default
  const resolvedBase = (basePrompt || DEFAULT_BASE_PROMPT).replaceAll('{language}', langName)
  parts.push(resolvedBase)

  // Language-wide style rules (always applied, regardless of mode)
  if (languageRules && languageRules.length > 0) {
    const ruleList = languageRules.map((r) => `- ${r}`).join('\n')
    parts.push(`${langName} style rules to follow:\n${ruleList}`)
  }

  // Condensation for long-word languages
  if (LONG_WORD_LANGUAGES.includes(targetLanguage)) {
    parts.push(
      `${langName} may produce longer words or phrases. ` +
      `If the translated text would exceed the original text boundaries, condense the phrasing while preserving the meaning.`
    )
  }

  // Precision mode: contextual glossary hints filtered for this specific image
  if (glossaryHints && glossaryHints.length > 0) {
    const hintList = glossaryHints.map((h) => `- ${h}`).join('\n')
    parts.push(`Glossary guidance for this image (preferred formulations):\n${hintList}`)
    return parts.join('\n\n')
  }

  // Standard mode: full glossary term list
  if (glossaryTerms && glossaryTerms.length > 0) {
    const termList = glossaryTerms
      .map((t) => `"${t.source}" -> "${t.target}"`)
      .join(', ')
    parts.push(`Use these specific translations: ${termList}`)
  }

  return parts.join('\n\n')
}
